FROM ubi8:8.5
MAINTAINER Diego Calbo <dcalbo@mbts.tech>
LABEL description="A custom Apache image" \
      version="v0.1-beta"
RUN yum update -y && yum install httpd --nodocs -y && yum install -y unzip && yum clean all
COPY ./src.zip /tmp/
RUN unzip /tmp/src.zip -d /tmp/ && cp -R /tmp/src/* /var/www/html/
# RUN echo "Hello from Containerfile" > /var/www/html/index.html
EXPOSE 80
CMD ["httpd", "-D", "FOREGROUND"]
