FROM docker.io/farrout/jboss-base:7.2
MAINTAINER Chandra Prakash < cprakash@qcsdclabs.com >
LABEL description="EX180 exam setup"

USER root

RUN mkdir -p /opt/jboss
COPY jboss-eap-7.2.0.zip /opt/jboss/ 
RUN unzip /opt/jboss/jboss-eap-7.2.0.zip -d /opt/jboss/

RUN chown -R jboss:jboss /opt/jboss  && \
    chmod -R 755 /opt/jboss

CMD ["/opt/jboss/jboss-eap-7.2/bin/add-user.sh -u chandra redhat"]

ENV JBOSS_HOME="/opt/jboss/jboss-eap-7.2"
USER jboss

EXPOSE 80 8080 9990 9999
CMD ["/opt/jboss/jboss-eap-7.2/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
